### ISSUE TITLE
Share roadmap

### ISSUE THREAD

**Issue by baseplate-admin** [emmyarty/dxsvelte#8]
Hi,

it's me again. I have a small request. 

Can we make a roadmap to have a clear goal ( and maybe some new contributions ) for this project?

Thanks :D

**Comment by emmyarty** [comment]
Hey again! Absolutely. I've only recently managed to make some time for it again, I've taken on quite a few projects running concurrently but one of them is nearing completion so I've had a *little* bit more time which is nice. A roadmap sounds like a good plan to me.

What I've been working on lately is actually porting the whole project across to Vite. I tried (and failed) to get PostCSS (and therefore Tailwind) working properly, and the way compilation is currently handled just doesn't leave a lot of room for user extendibility.

Once the port's ready, it ought to be a lot simpler for others to contribute to it, and we'll get better (though always slightly incomplete) interop with the SvelteKit ecosystem.

If all goes well, it'll land either this weekend or the next.

Have you got any contribution ideas in mind, or specific missing features which are presently preventing this project from working as a real-world solution that you wanted to raise?

**Comment by baseplate-admin** [comment]
> Have you got any contribution ideas in mind, or specific missing features which are presently preventing this project from working as a real-world solution that you wanted to raise?

The missing tailwind and vite integration is

**Comment by baseplate-admin** [comment]
Hi thanks for responding :P 


> Have you got any contribution ideas in mind, or specific missing features which are presently preventing this project from working as a real-world solution that you wanted to raise?

The missing `tailwind` and `vite` integration is the main let down for me :). ( since the [project i am working on](https://github.com/baseplate-admin/CoreProject-V3-UI) is using actively uses both [tailwind](https://github.com/baseplate-admin/CoreProject-V3-UI/blob/3612a9dfdee86540b0dceb5643cdc4b323c1d441/package.json#L62) and [vite](https://github.com/baseplate-admin/CoreProject-V3-UI/blob/3612a9dfdee86540b0dceb5643cdc4b323c1d441/package.json#L66) )

---

Other than that one more issue i have seen is does this project do tree shaking? Splitting into multiple chunks ? ( or maybe  i have misconfigured my project ? )


Thanks again :D

**Comment by emmyarty** [comment]
Makes sense; I use Tailwind myself so not having it implemented has always been one of the biggest things making it feel 'unfinished' to me as well.

Regarding tree-shaking, I'd expect it to be working out of the box as it's a default in ESBuild when bundling is enabled - which it definitely is.

Splitting into multiple chunks hasn't been on the agenda though, should we revisit that once the port is done? Because of the way I had the view components indexed, it hasn't been possible... but now, I think I have an idea of how I might work that one in.

Btw, we're on track for a weekend preview release. All the hard stuff is done, and it technically works, just gotta trim some fat and juggle a few things around so it's not painful to use.

**Comment by emmyarty** [comment]
Check it out! I'm tapped out for the weekend I think haha.

SSR is temporarily disabled, it will absolutely come back very soon so this isn't a main release yet. The overall experience of installing it should be much smoother now as well.

If you want to get started with it, within a Django project run
```
npx dxsvelte@alpha
```

I haven't got the energy to update the documentation but it should be largely the same. Compile command is now:
```
npm run build
```

But all in all, we can finally use Tailwind - and the codebase should be much clearer than it was. I'll give it all a reorganisation soon for clarity.

**Comment by baseplate-admin** [comment]
That's awesome. Well done. I might finally be able to deploy  `dxsvelte` in a production grade project :P

**Comment by emmyarty** [comment]
As long as I restore SSR before you finish your project 😂

**Comment by baseplate-admin** [comment]
Honestly i am a bit fade up on django not having a good ssr option. 

Maybe this project will hit the moon with a good marketing ( i honestly am hopeful 🤞 )

**Comment by baseplate-admin** [comment]
Hi i took a look. But i ran into this 

```typescript
    ~/Pr/test/coreproject  npx dxsvelte@alpha                           ✔ 
node:fs:592
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/home/baseplate-admin/.npm/_npx/9ec09851a3195573/node_modules/figlet/fonts/slant.flf'
    at Object.openSync (node:fs:592:3)
    at Object.readFileSync (node:fs:460:35)
    at figlet.loadFontSync (/home/baseplate-admin/.npm/_npx/9ec09851a3195573/node_modules/figlet/lib/node-figlet.js:52:21)
    at me.textSync (/home/baseplate-admin/.npm/_npx/9ec09851a3195573/node_modules/figlet/lib/figlet.js:1203:39)
    at main (file:///home/baseplate-admin/.npm/_npx/9ec09851a3195573/node_modules/dxsvelte/dist/configurator.js:814:12)
    at file:///home/baseplate-admin/.npm/_npx/9ec09851a3195573/node_modules/dxsvelte/dist/configurator.js:856:3
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:246:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/baseplate-admin/.npm/_npx/9ec09851a3195573/node_modules/figlet/fonts/slant.flf'
}

Node.js v20.3.1

```

**Comment by emmyarty** [comment]
should be sorted

**Comment by baseplate-admin** [comment]
Yayy !! 🥳

**Comment by emmyarty** [comment]
Aaaand SSR's back, with that I think I'll close this issue for now - going to start working on a more formal version release and get this out of alpha next after a few smaller loose ends are tied up.
